### ISSUE TITLE
R17 to -12V connection and GND-Earth link - A1200 PSU

### ISSUE THREAD

**Issue by ChewChewie** [nbolton/amiga#1]
Hi,

Great work.  This really helped me troubleshooting the -12V supply on my A1200 PSU, so I would like to contribute with what I hope is useful information…..

1. My PSU is Pt No. 391029-03, but has the same PCB as shown in this repository - Pt No. 30501-001 A.  I guess Commodore used various PCBs in various PSU enclosures and it may be better to say that PCB 30501-001 A may be found in PSU Pt Nos 391029-02 and 391029-03.
2. Your schematic doesn’t quite reflect the configuration of the circuit.  On the PCB:
     a. The white wire (-12V) connects at the junction of L2, C16, R17 and the other side (RHS) of R17 is connected to GND.
     b. There is a shorting link between earth and GND.  This is adjacent to C16 on the PCB.

**Comment by nbolton** [comment]
Thanks for the observations! I'm glad you found the [A1200 PSU schematic](https://github.com/nbolton/amiga/tree/main/hardware/a1200-psu) helpful.

Are you able to highlight these observations on the PCB image? I can't quite spot what you're referring to. Maybe if you could also highlight on the schematic, that'd be easier to see.

> a. The white wire (-12V) connects at the junction of L2, C16, R17 and the other side (RHS) of R17 is connected to GND.
> b. There is a shorting link between earth and GND. This is adjacent to C16 on the PCB.

![image](https://user-images.githubusercontent.com/313427/231442470-71778c68-c9ba-4463-a70e-3a95b15caf0c.png)

![image](https://user-images.githubusercontent.com/313427/231442868-5a12f938-7995-42db-a930-a775c2437591.png)

**Comment by ChewChewie** [comment]
I’m referring to differences between your schematic and your PCB from the original PCB so I have marked up the picture of the underside of the original PCB.  
If you inspect your original PCB you should spot the link between shield and GND in the area shown and you’ll note that what you refer to as R17 on your schematic is connected to GND and the -12V wire connects to the other side of R17 at the junction of L2, C16, R17 -  this is where your schematic and PCB differs from the original PCB.  
I hope that makes sense.  

![Inkeda1200-psu-pcb-back (2)](https://user-images.githubusercontent.com/111243822/232098898-32a3c485-ad8e-439a-9fce-02ce650bb4fa.jpg)

**Comment by nbolton** [comment]
Ah, the Earth-GND link isn't visible on my photo, and the PSU is currently in use.

<img width="193" alt="Screenshot 2023-04-18 at 11 38 31" src="https://user-images.githubusercontent.com/313427/232752570-524ed761-be6a-4b41-9edd-ea15ea8f771e.png">

But yes, I do see this on another random photo I found on the web! It shows the link...

![image](https://user-images.githubusercontent.com/313427/232743275-c311cb2b-e653-43f8-bb2c-470179b968a6.png)

Looks like the -12 V connection is actually like so... what do you think? 

<img width="768" alt="Screenshot 2023-04-18 at 11 16 45" src="https://user-images.githubusercontent.com/313427/232747424-3ee2171e-87ac-4c87-b158-79e1027b3474.png">

<img width="478" alt="Screenshot 2023-04-18 at 11 27 49" src="https://user-images.githubusercontent.com/313427/232750063-df776177-b772-478a-83c5-48de68bcd7f9.png">

I made a PR: https://github.com/nbolton/amiga/pull/2

If the above looks good, I'll go ahead and merge.

Edit: I'm scratching my head why the R17 (330R) is actually needed. Looks like it sits there leaking 36.36 mA.

**Comment by ChewChewie** [comment]
Here’s a shot of my PSU which looks the same as the random photo, but without the leaking electrolyte - I cleaned that up :-) 

![20230313_131515](https://user-images.githubusercontent.com/111243822/232897410-b519dc06-1d05-4d74-bf8b-a8d05d57d3b2.jpg)

Yep, I think your updated schematic and PCB captures the -12V side accurately.

The 330R load is a bit of a mystery.  I know the -12V is only lightly used by the audio and the serial port so perhaps some additional load is needed to keep sufficient current flowing for this SMPS to operate correctly.

**Comment by nbolton** [comment]
> load is needed to keep sufficient current flowing for this SMPS to operate correctly

Sounds about right, I noticed that the -12 voltage changes quite a lot depending on load, so perhaps this is just a cheap way to balance it out... or maybe it's to get the PWM IC going? Even with this, without a computer providing load, I notice that the PWM pulses at a very slow 'idle' speed (hence the ticking you can hear, which I think is just magnetostriction on the coil). All wild guesses!

I'll merge that PR. Thanks for your help!
